# Generated by Django 2.2.6 on 2020-11-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='date_joined',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
