# Generated by Django 2.2.6 on 2020-11-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0002_auto_20201130_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
