# Generated by Django 2.2.6 on 2020-11-29 19:37

from django.db import migrations, models
import pytz


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0003_vendor_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='date_joined',
            field=models.DateTimeField(default=pytz.timezone),
        ),
    ]
